### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cwoandrew** [raina-wu/DynRigBuilder#1]
# Error: ImportError: file <maya console> line 1: No module named DynRigBuilder #

**Comment by Mogiee** [comment]
make sure its still in the folders...."\Documents\maya\scripts\DynRigBuilder\dynrigbuilder" I was getting that error too but I tried moving the folder again and renamed "DynRigBuilder" without "-master" on the end and now it at least runs

But now I'm getting this error when I run the import - 
import DynRigBuilder
DynRigBuilder.show() 
# Error: NameError: file  line 54: global name 'QUiLoader' is not defined # 

So yeah I hope that works for you... but you might get this ^ right after fixing it

**Comment by cwoandrew** [comment]
Wish the developer can fix the problem or have a guideline. Thank you so much for this great tool!

**Comment by raina-wu** [comment]
Yeah I guess if you choose to download zip instead of git clone, a "-master" suffix will be added to the folder name. Just as @Mogiee mentioned, copy the root folder into your maya script folder and make sure the folder name stay the same. 
I've convert the .ui file into .py file, in order to fixed the 'QUiLoader' not defined issue you mentioned. Give it a try and let me know if it works. Thanks.

**Comment by cwoandrew** [comment]
DynRigBuilder\dynrigbuilder\dynrigbuilderui.py line 10: No module named PySide #

**Comment by Mogiee** [comment]
@cwoandrew  you probably have a newer version of Maya with PySide2 I got the same error.  I'm on Maya  2018 and I got it running with this conversion:
```
import sys

if 'PySide2' in sys.modules:
    sys.modules['PySide'] = sys.modules['PySide2']
    sys.modules['shiboken'] = sys.modules['shiboken2'] 
    import pyside2uic
    sys.modules['pysideuic'] = sys.modules['pyside2uic']
    sys.modules['PySide.QtGui'] = sys.modules['PySide2.QtGui']
    sys.modules['PySide.QtCore'] = sys.modules['PySide2.QtCore']
    sys.modules["PySide.QtGui"].__dict__.update(sys.modules["PySide2.QtWidgets"].__dict__)
    import PySide
    from PySide import QtGui, QtCore, QtWidgets
    setattr(sys.modules["PySide.QtGui"], "QApplication", sys.modules["PySide2.QtWidgets"].QApplication)    
    setattr(sys.modules["PySide.QtGui"].QApplication, "UnicodeUTF8", -1)
    setattr(sys.modules["PySide.QtGui"], "QSortFilterProxyModel", 
    sys.modules["PySide2.QtCore"].QSortFilterProxyModel)    
    setattr(sys.modules["PySide.QtGui"].QHeaderView, "setResizeMode", 
    sys.modules["PySide2.QtWidgets"].QHeaderView.setSectionResizeMode)    
    
import DynRigBuilder
DynRigBuilder.show() 

```
(Also @raina-wu it's a rad script thanks!)

**Comment by cwoandrew** [comment]
@Mogiee, ^^ OIC let me try, thx alot!

**Comment by cwoandrew** [comment]
@Mogiee 
Great! it works!
@raina-wu 
it is great if you can include the PySide2 support for maya 2018

thx very much!
